version: "3"
services:
  app:
    build: .
    ports:
      - "5001:5000"
    container_name: app
    env_file:
      - ./.env
    volumes:
      - ./app:/usr/src/app
    command: flask run --host=0.0.0.0
